# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - Thamco-product

on:
  push:
    branches:
      - Mains
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://thamcoregistry/
        username: ${{ secrets.AzureAppService_ContainerUsername_ffa7a7d86bad4097946b34d159eb804b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_9583fd81e43344b8837c8314413db99f }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: thamcoregistry/${{ secrets.AzureAppService_ContainerUsername_ffa7a7d86bad4097946b34d159eb804b }}/thamcregistry.azurecr.io/productservice:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Thamco-product'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e15327904cea4a4987516bdbbf4b9093 }}
        images: 'thamcoregistry/${{ secrets.AzureAppService_ContainerUsername_ffa7a7d86bad4097946b34d159eb804b }}/thamcregistry.azurecr.io/productservice:${{ github.sha }}'